# Generated by Django 4.1.7 on 2023-04-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=51)),
                ('email', models.CharField(max_length=50)),
                ('moblie_No', models.BigIntegerField()),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Admin_Registration_Master',
            },
        ),
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circle_code', models.IntegerField(default=0, unique=True)),
                ('circle_name', models.CharField(max_length=50)),
                ('circle_contact', models.CharField(max_length=50)),
                ('office_id', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Circle_Master',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('message', models.TextField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'feedback_master',
            },
        ),
        migrations.CreateModel(
            name='File_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('file_name', models.CharField(max_length=30)),
                ('file_Description', models.CharField(max_length=100)),
                ('file_Location', models.CharField(max_length=30)),
                ('file_Created_Date', models.DateField()),
                ('file_Status', models.CharField(max_length=30)),
                ('file_Reject_Because', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'File_Status',
            },
        ),
        migrations.CreateModel(
            name='User_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('moblie_No', models.BigIntegerField()),
                ('pwd', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'user_registration_master',
            },
        ),
    ]
