# Generated by Django 4.1.7 on 2023-04-18 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_registration',
            old_name='pwd',
            new_name='password',
        ),
    ]
