# Generated by Django 4.1.7 on 2023-04-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_pwd_user_registration_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=30)),
                ('scode', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Design_Master',
            },
        ),
    ]
