# Generated by Django 4.1.7 on 2023-04-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_design'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_code', models.IntegerField(unique=True)),
                ('circle_code', models.IntegerField()),
                ('division_name', models.CharField(max_length=50)),
                ('division_contact', models.CharField(max_length=50)),
                ('office_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Division_Master',
            },
        ),
    ]
