# Generated by Django 4.1.7 on 2023-04-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_subdivision'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdivision_code', models.IntegerField(default=0)),
                ('division_code', models.IntegerField(default=0)),
                ('circle_code', models.IntegerField(default=0)),
                ('office_code', models.IntegerField(default=5)),
                ('department_id', models.IntegerField(default=0)),
                ('design_id', models.IntegerField(default=0)),
                ('role_id', models.IntegerField(default=0)),
                ('uname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('adminname', models.CharField(max_length=50)),
                ('emp_no', models.CharField(default='null', max_length=10, null=True)),
                ('email', models.CharField(default='null', max_length=100, null=True)),
                ('phone', models.IntegerField(default='null', null=True)),
                ('address', models.TextField(default='null', null=True)),
                ('city', models.CharField(default='null', max_length=15, null=True)),
                ('state', models.CharField(default='null', max_length=15, null=True)),
                ('active', models.CharField(default='Y', max_length=1)),
                ('deactive_remarks', models.CharField(default='null', max_length=100, null=True)),
                ('deactive_date', models.DateTimeField(default='null', null=True)),
                ('last_update_user_id', models.CharField(default='null', max_length=50, null=True)),
                ('last_update_date', models.DateTimeField()),
                ('last_update_ip', models.CharField(default='null', max_length=20, null=True)),
                ('cdeptid', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'User_Master',
            },
        ),
    ]
