# Generated by Django 4.1.7 on 2023-04-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scode', models.CharField(max_length=10)),
                ('sid', models.IntegerField()),
                ('dept_id', models.SmallIntegerField()),
                ('deign_id', models.SmallIntegerField()),
                ('file_name', models.CharField(max_length=100)),
                ('file_title', models.CharField(max_length=500)),
                ('file_desc', models.TextField(default='null', null=True)),
                ('file_created_date', models.DateTimeField()),
                ('file_put_user_id', models.IntegerField()),
                ('file_put_uname', models.CharField(max_length=50)),
                ('file_status', models.CharField(default='create', max_length=10, null=True)),
                ('file_status_remarks', models.TextField(default='null', null=True)),
                ('file_status_date', models.DateTimeField()),
                ('last_update_user_id', models.IntegerField(default='null', null=True)),
                ('last_update_date', models.TimeField()),
                ('last_update_ip', models.CharField(default='null', max_length=20, null=True)),
            ],
            options={
                'db_table': 'File_Create',
            },
        ),
        migrations.DeleteModel(
            name='File_Status',
        ),
    ]
