# Generated by Django 4.1.7 on 2023-04-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_registration',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='user_registration',
            name='lastname',
        ),
        migrations.AddField(
            model_name='user_registration',
            name='username',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
