# Generated by Django 4.1.7 on 2023-04-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_department_cddept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='division_contact',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
