# Generated by Django 4.1.7 on 2023-04-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_division_division_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='division_contact',
            field=models.CharField(default='NULL', max_length=50, null=True),
        ),
    ]
