# Generated by Django 4.1.7 on 2023-04-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_division_division_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdivision',
            name='subdivision_contact',
            field=models.CharField(default='NULL', max_length=50),
        ),
    ]
