# Generated by Django 4.1.7 on 2023-04-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_subdivision_subdivision_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cdeptid',
            field=models.SmallIntegerField(default='0'),
        ),
    ]
