# Generated by Django 4.1.7 on 2023-04-27 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_user_deactive_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file_create',
            old_name='deign_id',
            new_name='design_id',
        ),
    ]
