# Generated by Django 4.1.7 on 2023-04-29 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_rename_deign_id_file_create_design_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='receiver_uname',
            new_name='receive_uname',
        ),
    ]
