# Generated by Django 4.1.7 on 2023-04-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_rename_receiver_uname_notification_receive_uname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='0', max_length=11, null=True),
        ),
    ]
