# Generated by Django 4.1.7 on 2023-05-03 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_user_phone'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subdivision',
            table='Subdivision_Master',
        ),
    ]
