# Generated by Django 4.1.7 on 2023-05-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_alter_subdivision_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_create',
            name='document',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
